force-app/main/default/objects/BWP_Price__c/BWP_Price__c.object-meta.xml
<CustomObject>
    <label>BWP Price</label>
    <nameField>
        <label>BWP Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>BWP Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BWP_Price__c/fields/Price_Id__c.field-meta.xml
<CustomField>
    <fullName>Price_Id__c</fullName>
    <externalId>true</externalId>
    <label>Price Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BWP_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>BWP_Product__c</referenceTo>
    <relationshipLabel>Prices (Breadwinner Billing)</relationshipLabel>
    <relationshipName>Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BWP_Price__c/fields/Recurring_Interval__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Interval__c</fullName>
    <label>Recurring Interval</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/BWP_Price__c/fields/Recurring_Interval_Count__c.field-meta.xml
<CustomField>
    <fullName>Recurring_Interval_Count__c</fullName>
    <label>Recurring Interval Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BWP_Price__c/fields/Unit_Amount__c.field-meta.xml
<CustomField>
    <fullName>Unit_Amount__c</fullName>
    <label>Unit Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Selector_BWP_Price.cls
public with sharing class Selector_BWP_Price extends QuerySelector {
    // Core list of fields
    public static List<Schema.SObjectField> FIELD_LIST {
        get {
            if (FIELD_LIST == null) {
                FIELD_LIST = new List<Schema.SObjectField>{
                    BWP_Price__c.Id,
                    BWP_Price__c.Name,
                    BWP_Price__c.Active__c,
                    BWP_Price__c.Created_Date_in_Processor__c,
                    BWP_Price__c.Created_Via__c,
                    BWP_Price__c.Currency__c,
                    BWP_Price__c.Price_Id__c,
                    BWP_Price__c.Processor_Org_Id__c,
                    BWP_Price__c.Product__c,
                    BWP_Price__c.Recurring_Interval__c,
                    BWP_Price__c.Recurring_Interval_Count__c,
                    BWP_Price__c.Type__c,
                    BWP_Price__c.Unit_Amount__c
                };
            }
            return FIELD_LIST;
        }
        private set;
    }

    public Selector_BWP_Price() {
        this(true, true, true);
    }
    public Selector_BWP_Price(Boolean enforceRead, Boolean enforceFLS, Boolean throwFLSException) {
        super(enforceRead, enforceFLS, throwFLSException);
    }
    
    public override Schema.SObjectType getSObjectType() {
        return BWP_Price__c.SObjectType;
    }

    private List<Schema.SObjectField> sObjectFieldList;
    public override List<Schema.SObjectField> getSObjectFieldList() {
        return sObjectFieldList != null ? sObjectFieldList : FIELD_LIST;
    }
    /**
     * Allows the calling class to override the default FIELD_LIST
     * @param fieldList list of field that will be passed into the query
     */
    public void setSObjectFieldList(List<Schema.SObjectField> fieldList){
        this.sObjectFieldList = fieldList;
    }

    private String orderBy;
    public override String getOrderBy() {
        return String.isBlank(orderBy) ? 'Name ASC' : orderBy;
    }

    public List<BWP_Price__c> selectByPriceId(Set<String> idSet, List<String> relatedFields){
        QueryBuilder qb = newQueryBuilderWithRelatedFields(relatedFields);
        qb.setCondition('Price_Id__c IN :idSet');
        return (List<BWP_Price__c>) Database.query(qb.toSOQL());
    }
}